[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  # This redirects any path to the root URL (index.html)
  from = "/*"
  to = "/index.html"
  status = 200

# Explicitly serve robots.txt and sitemap.xml directly
[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200