
apiVersion: "v1"
kind: "Service"
metadata:
  name: "portfolio-frontend-service"
  namespace: "default"
  labels:
    app: "portfolio-frontend"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: "portfolio-frontend"
  type: "NodePort"
