name: Auto Create Merge Requests

on:
  push:
    branches:
      - dev

jobs:
  create-merge-requests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Create Merge Request to Master
        run: |
          git fetch origin master
          git checkout -b merge-dev-to-master
          git merge origin/dev
          git push origin merge-dev-to-master:refs/heads/merge-dev-to-master
          gh pr create --base master --head merge-dev-to-master --title "Merge dev to master" --body "Auto-created merge request from dev to master"

      - name: Create Merge Request to Production
        run: |
          git fetch origin production
          git checkout -b merge-dev-to-production
          git merge origin/dev
          git push origin merge-dev-to-production:refs/heads/merge-dev-to-production
          gh pr create --base production --head merge-dev-to-production --title "Merge dev to production" --body "Auto-created merge request from dev to production"
