name: Create Pull Request

on:
  push:
    branches: [ dev ]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set master branch
        id: set-master-branch
        run: |
          master_branch=master  # Replace with your desired env variable name
          if [ -z "$master_branch" ]; then
            echo "master_BRANCH environment variable is not set. Defaulting to 'master'"
            master_branch="master"
          fi
          echo "::set-output name=master_branch::$master_branch"

      - name: Create pull request on master
        uses: actions/create-pull-request@v3
        with:
          title: "Updates from DEV branch"
          body: "Pushed changes from DEV branch for review."
          master: ${{ steps.set-master-branch.outputs.master_branch }}
          origin: ${{ github.sha }}

      - name: Set production branch
        id: set-production-branch
        run: |
          production_branch=production  # Replace with your desired env variable name
          if [ -z "$production_branch" ]; then
            echo "production_BRANCH environment variable is not set. Defaulting to 'production'"
            production_branch="production"
          fi
          echo "::set-output name=production_branch::$production_branch"

      - name: Create pull request on production
        uses: actions/create-pull-request@v3
        with:
          title: "Updates from DEV branch"
          body: "Pushed changes from DEV branch for review."
          production: ${{ steps.set-production-branch.outputs.production_branch }}
          origin: ${{ github.sha }}
